version: '2.1'
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      args:
        databaseName: 'golang-db'
    ports:
      - 8000:8000
    #volumes:
    #  - .:/src/go_rest
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - /data/db
    ports:
      - 27017:27017